### PR TITLE
Flake8 peeves

### PR DESCRIPTION
**Pull request by ilveroluca**
A few small changes to make flake8 more palatable, without relaxing its checks.

### CODE REVIEW

**Comment by simleo** [comment]
I agree that seeing all those lines from flake8 is annoying. However, the problem with the silent mode is that it's *really* silent, i.e., nothing is written. This means that if for some reason flake8 does not run at all we get the same result we would if it ran successfully.

**Comment by ilveroluca** [comment]
If something's wrong it should exit with an error and block the
installation. Likewise if the command doesn't run (e.g., not found because
of an installation problem).
Il 09/mar/2016 18:39, "Simone Leo" <notifications@github.com> ha scritto:

**Comment by simleo** [comment]
If there is any kind of error we'll notice, sure. I was thinking about a situation where we accidentally delete the line that runs flake8 from the travis script. But I guess that's a bit far-fetched.

What's the benefit of having tox.ini rather than setup.cfg?

**Comment by ilveroluca** [comment]
> What's the benefit of having tox.ini rather than setup.cfg?

Tab-completion works on on the filename `setup.py`

**Comment by simleo** [comment]
Out of sync with the latest dev branch (currently named `develop-py3`), where flake8 is the first thing that runs anyway, so we should be fine. `-v` still present ATM, but we can remove it later. Closing.

**Pull request closed without merging**
