### PR TITLE
Changes for python2.6

### PR DESCRIPTION
**Pull request by vkuznet**
Fix positional argument in submit and added get_logger helper function to deal with logger APIs under different version of python.

### CODE REVIEW

**Comment by vkuznet** [comment]
Hi, I'm not familiar with pydoop dev. cycle and made PR against its master, probably it should go against develop branch. Anyway, I found that our local cluster runs python 2.6 and pydoop uses new logger getChild API which only available in python 2.7. I fixed that via get_logger helper function which checks python version. I also fixed bug in submit.py. If you need another PR against develop branch please let me know and I can do it.

**Comment by vkuznet** [comment]
or you can take changes I made (https://github.com/crs4/pydoop/commit/81d885add406d38c3b6cd5023d5e969346b218d4) and apply them by yourself to whatever branch is necessary.

**Comment by simleo** [comment]
Hi,

please rebase your changes onto the develop branch.

Sorry about this, we should clarify the dev cycle in a "how to contribute" doc.

**Comment by vkuznet** [comment]
I made another PR: https://github.com/crs4/pydoop/pull/178/files, please review. The strange part that it shows correct file changes, but conversation/commits history shows other (not mine) commits. Please review and let me know. I checked that diff, https://github.com/crs4/pydoop/pull/178.diff shows correct (mine) changes though. Feel free to close this PR.

**Comment by simleo** [comment]
A simple way to get a clean PR if you know that the diff is correct is to apply it to the current develop branch and make a single commit with those changes. Something like:

```
git checkout develop
wget https://patch-diff.githubusercontent.com/raw/crs4/pydoop/pull/178.diff
git apply 178.diff
git commit -m "fix Python 2.6 compatibility"
```

I could create such a PR myself, but you would lose credit for the changes.

**Comment by vkuznet** [comment]
Simone, I don't need credits, feel free to apply changes. I'm happy to help
with code and stuff.

The branch I have has some issues and I'm not sure how to properly resolve
them (I fork pydoop and did):

```
git remote -v
upstream	git@github.com:crs4/pydoop.git (fetch)
upstream	git@github.com:crs4/pydoop.git (push)

git fetch ustream
git rebase upstream/develop
First, rewinding head to replay your work on top of it...
Applying: hotfix on pipes arguments passed from pydoop script #993
Using index info to reconstruct a base tree...
M	pydoop/app/main.py
M	pydoop/app/script.py
Falling back to patching base and 3-way merge...
Auto-merging pydoop/app/script.py
CONFLICT (content): Merge conflict in pydoop/app/script.py
Auto-merging pydoop/app/main.py
CONFLICT (content): Merge conflict in pydoop/app/main.py
error: Failed to merge in the changes.
Patch failed at 0001 hotfix on pipes arguments passed from pydoop script #993
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

So, something is wrong elsewhere and I better off to delete my branch and re-fork it again later.
Best,
Valentin.

**Comment by ilveroluca** [comment]
Replaced by #179 which fixes issues with this PR's commit history.

**Comment by ilveroluca** [comment]
I used @simleo's trick with the `--author` option to `

**Comment by ilveroluca** [comment]
I used @simleo's trick with the addition of the `--author` option to `git commit` to make everyone happy :-)

**Pull request closed without merging**
